### ISSUE TITLE
New member request

### ISSUE THREAD

**Issue by yumnadahab1** [GWCoders/studyGroup#2]
Welcome!

If you are asking to be added to the list of contributors in `_data/contributors.yml`, please include the following information in your issue: 

```
- name: Yumna Dahab
  degree: GWU , Major : Systems Engineering , Minor: Public Health
  github: yumnadahab1
  interests:
    - Photography, travel, nature

```
